### ISSUE TITLE
Colud you provided more imformation about this project?

### ISSUE THREAD

**Issue by heishanmao** [marcos-acosta/USA-mapping#1]
Actually, I tried to plot this kind of pictures and found you had finished it. But, this can not meet my requirements. So I'd like to modify this code. Such as add the State abbreviation displayed on each block. So, could you give me more information about how to work with it?  Where I can find the 'help document' ?
thanks.

**Comment by marcos-acosta** [comment]
Hi heishanmao, this repo was really only a test run for me as part of a project I'm working on, but information about the plotly package for plotting choropleth maps can be found [here](https://plotly.com/python/choropleth-maps/). Hopefully this should help with any features you'd like to add.

**Comment by heishanmao** [comment]
Thank you very much, marcos-acosta. It is so important to me.
